version: '3'

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: performance
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  spring:
    image: openjdk:8
    ports:
      - 8080:8080
      - 4444:4444
    volumes:
      - ./spring-mysql-performance-0.0.1-SNAPSHOT.jar:/usr/src/spring-mysql-performance-0.0.1-SNAPSHOT.jar
      - ./data:/usr/src/data
      - ./ServerAgent-2.2.3:/usr/ServerAgent-2.2.3
    entrypoint:
      - bash
      - -c
      - "chmod u+x /usr/ServerAgent-2.2.3/startAgent.sh && /usr/ServerAgent-2.2.3/startAgent.sh && java -jar /usr/src/spring-mysql-performance-0.0.1-SNAPSHOT.jar"

  taurus:
    image: blazemeter/taurus
    volumes:
      - ./:/bzt-configs
      - ./results:/tmp
    entrypoint:
      - bash
      - -c
      - "chmod u+x /bzt-configs/test.sh && /bzt-configs/test.sh"