version: '3'

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: performance
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  node:
    image: node
    ports:
      - 3000:3000
      - 4444:4444
    volumes:
      - ./node-mysql-performance:/usr/src/node-mysql-performance
      - ./ServerAgent-2.2.3:/usr/ServerAgent-2.2.3
    working_dir: /usr/src/node-mysql-performance
    entrypoint:
      - bash
      - -c
      - "chmod u+x /usr/ServerAgent-2.2.3/startAgent.sh && chmod u+x /usr/ServerAgent-2.2.3/jdk-13.0.1/bin/java && /usr/ServerAgent-2.2.3/startAgent.sh && npm start"
      
  taurus:
    image: blazemeter/taurus
    volumes:
      - ./:/bzt-configs
      - ./results:/tmp
    entrypoint:
      - bash
      - -c
      - "chmod u+x /bzt-configs/test.sh && /bzt-configs/test.sh"